accept = [200, 403, 429]
exclude = [ 
    '(?x).*profiles.ucl.ac.uk.*/thumbnail',   # People may not have a profile image.
    '(?x).*github-readme-stats.vercel.app.*', # Returns 503 for some reason
    '(?x).*127.0.0.1.*',                      # This is a local address
    '(?x).*liveuclac.sharepoint.com/sites/*', # SharePoint pages will need UCL credentials.
]
