# Checks for broken links with Lychee
name: Link Checker

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  linkChecker:
    timeout-minutes: 2
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
        # Currently just checks internal links by excluding anything starting with "http"
        with:
          args: "--no-progress --verbose -- ."
          fail: true
          jobSummary: true
